---
mysql_vendor: mysql
mysql_origin: upstream
mysql_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + openio_bind_interface]['ipv4']['address'] }}"
mysql_import_timezones: false
mysql_root_password: "{{ openio_database_root_password }}"

mysql_databases:
  - name: keystone
mysql_users:
  - name: keystone
    password: "{{ openio_database_keystone_password }}"
    privileges: 'keystone.*:ALL'
    host: '%'

  - name: keystone
    password: "{{ openio_database_keystone_password }}"
    privileges: '*.*:SUPER'
    append_privileges: "yes"
    host: '%'
...
