---
# Default inteface or a bonding interface
openio_keystone_nodes_group: keystone
openio_keystone_bind_interface: "{{ ansible_default_ipv4.alias }}"
openio_keystone_bind_virtual_address: "172.17.0.100"
openio_keystone_namespace: "{{ namespace }}"
openio_keystone_cloudname: "{{ namespace }}"

openio_keystone_config_cache_memcache_servers: "{{ hostvars[inventory_hostname]['ansible_' + openio_keystone_bind_interface]['ipv4']['address'] }}:6019"
openio_memcached_serviceid: "0"
openio_memcached_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + openio_keystone_bind_interface]['ipv4']['address'] }}"

openio_keystone_services_to_bootstrap:
  - name: keystone
    user: admin
    password: "ADMIN_PASS"
    project: admin
    role: admin
    regionid: RegionOne
    adminurl: "http://{{ openio_keystone_bind_virtual_address }}:35357"
    publicurl: "http://{{ openio_keystone_bind_virtual_address }}:5000"
    internalurl: "http://{{ openio_keystone_bind_virtual_address }}:5000"

# MYSQL
openio_keystone_database_engine: mysql
openio_keystone_database_mysql_connection_password: "{{ hostvars[groups['db'][0]]['keystone_user_password'] }}"
openio_keystone_database_mysql_connection_address: "{{ hostvars[groups['db'][0]]['ansible_default_ipv4']['address'] }}"

openio_keystone_users:
  - name: demo
    password: DEMO_PASS
  - name: swift
    password: SWIFT_PASS
...
