---
- name: Check inventory
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/defaults.yml
  tasks:

    - name: Stop if ansible version is too low
      assert:
        that:
          - ansible_version.full|version_compare('2.4.0', '>=')
          - ansible_version.full|version_compare('2.6.0', '<')

#    - name: Stop if even number of zookeeper hosts
#      assert:
#        that: groups.zookeeper|length is not divisibleby 2
#      ignore_errors: "{{ openio_ignore_assert_errors }}"


- name: Check hosts
  hosts: all
  gather_facts: false
  become: false
  vars_files:
    - vars/defaults.yml
  tasks:

    - name: Install python for Ansible
      raw: >-
        test -e /usr/bin/python ||
        (apt -y update && apt install -y python-minimal)
      changed_when: false

    - name: Gathering facts
      setup:

    - name: Stop if non systemd OS type
      assert:
        that: ansible_service_mgr == "systemd"
      ignore_errors: "{{ openio_ignore_assert_errors }}"

    - name: Stop if unknown OS
      assert:
        that: ansible_distribution in openio_distribution_supported
      ignore_errors: "{{ openio_ignore_assert_errors }}"

    - name: Stop if SELinux activated
      assert:
        that: ansible_selinux.status == 'disabled'
      ignore_errors: "{{ openio_ignore_assert_errors }}"
      when: ansible_os_family == 'RedHat'

    - name: Stop if AppArmor activated
      assert:
        that: ansible_apparmor.status == 'disabled'
      ignore_errors: "{{ openio_ignore_assert_errors }}"

    # - name: Stop if firewalld activated
    #   assert:
    #     that: ????.status == 'disabled'
    #   ignore_errors: "{{ openio_ignore_assert_errors }}"

    # - name: Check APT policy
    #   assert:
    #     that: ????.status == 'disabled'
    #   ignore_errors: "{{ openio_ignore_assert_errors }}"

    - name: Stop if memory is too small for zookeepers
      assert:
        that: ansible_memtotal_mb >= 2000
      ignore_errors: "{{ openio_ignore_assert_errors }}"
      when: inventory_hostname in groups['zookeeper']

    - name: Stop if memory is too small for nodes
      assert:
        that: ansible_memtotal_mb >= 1000
      ignore_errors: "{{ openio_ignore_assert_errors }}"
      when: inventory_hostname in groups['rawx']

    # - name: Stop if ip var does not match local ips
    #   assert:
    #     that: ip in ansible_all_ipv4_addresses
    #   ignore_errors: "{{ openio_ignore_assert_errors }}"
    #   when: ip is defined

    # - name: Stop if access_ip is not pingable
    #   command: ping -c1 {{ ip }}
    #   when: ip is defined
    #   ignore_errors: "{{ openio_ignore_assert_errors }}"

    - name: Stop if swap enabled
      assert:
        that: ansible_swaptotal_mb == 0
      ignore_errors: "{{ openio_ignore_assert_errors }}"
      # when: inventory_hostname in groups['rawx']

    - name: Stop if kernel version is too low
      assert:
        that: ansible_kernel.split('-')[0]|version_compare('3.10', '>=')
      ignore_errors: "{{ openio_ignore_assert_errors }}"
...
