---
- name: Install OpenIO Conscience
  hosts: conscience
  gather_facts: false
  become: true
  vars_files:
    - vars/defaults.yml
    - vars/namespace.yml
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: conscience
      openio_conscience_namespace: "{{ namespace }}"
      openio_conscience_namespace_status: "standalone"
      openio_conscience_bind_port: "{{ conscience_port }}"
...
