---
- name: Install Conscience Agent
  hosts: openio
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: conscienceagent
      openio_conscienceagent_namespace: "{{ namespace }}"
      #openio_conscienceagent_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
