---
- name: Install OpenIO Conscience
  hosts: conscience
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: conscience
      openio_conscience_namespace: "{{ namespace }}"
      #openio_conscience_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
