---
- name: Install requirements
  hosts: all
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is defined

  roles:
    - role: repository
      openio_repository_products:
        sds:
          release: "{{ openio_sds_release }}"
    - role: ntp
#    - role: survivalkit
...
