---
- name: temporaire - Install keystone's external database
  hosts: db
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: mariadb
      #when: sql_engine == 'mysql' and ansible_os_family == 'RedHat'


- name: Install Openstack Keystone
  hosts: keystone
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: memcached
      openio_memcached_namespace: "{{ namespace }}"
      openio_memcached_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"

    - role: keystone
      openio_keystone_namespace: "{{ namespace }}"
      openio_keystone_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
