---
- name: Install OpenIO Meta0
  hosts: meta0
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: meta0
      openio_meta0_namespace: "{{ namespace }}"
      openio_meta0_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
