---
- name: Install OpenIO Meta1
  hosts: meta1
  gather_facts: false
  become: true
  vars_files:
    - vars/defaults.yml
    - vars/namespace.yml
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: repository
    - role: gridinit
      openio_gridinit_namespace: "{{ namespace }}"
    - role: meta1
      openio_meta1_namespace: "{{ namespace }}"
...
