---
- name: Install OpenIO Meta2
  hosts: meta2
  gather_facts: false
  become: true
  vars_files:
    - vars/defaults.yml
    - vars/namespace.yml
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: meta2
      openio_meta2_namespace: "{{ namespace }}"
...
