---
- name: Install OpenIO Meta0
  hosts: meta0
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: meta
      openio_meta_namespace: "{{ namespace }}"
      openio_meta_version: "{{ openio_sds_version }}"
...
