---
- name: Install OpenIO Meta0
  hosts: meta0
  gather_facts: false
  become: true
  vars_files:
    - vars/defaults.yml
    - vars/namespace.yml
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: meta0
      openio_meta0_namespace: "{{ namespace }}"
...
