---
- name: Install OpenIO Meta1
  hosts: meta1
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: meta1
      openio_meta1_namespace: "{{ namespace }}"
      openio_meta1_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
