---
- name: Install OpenIO Meta2
  hosts: meta1
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: meta
      openio_meta_namespace: "{{ namespace }}"
      openio_meta_mode: meta2
      openio_meta_version: "{{ openio_sds_version }}"
      #openio_meta_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
