---
- name: Install Proxy OIO
  hosts: openio
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: oioproxy
      openio_oioproxy_namespace: "{{ namespace }}"
      openio_oioproxy_serviceid: "{{ ansible_play_hosts.index(inventory_hostname) }}"
...
