---
- name: Install Proxy OIO
  hosts: openio
  gather_facts: false
  become: true
  vars_files:
    - vars/defaults.yml
    - vars/namespace.yml
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: oioproxy
      openio_oioproxy_namespace: "{{ namespace }}"
...    

...
