---
- name: Gather facts
  hosts: oioswift,keystone
  tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined

- name: Install Swift Gateway
  hosts: oioswift
  gather_facts: false
  become: true
  roles:
    - role: oioswift
      openio_oioswift_namespace: "{{ namespace }}"
      openio_oioswift_sds_version: "{{ openio_sds_version }}"
      openio_oioswift_version: "{{ openio_swift_version }}"
      openio_oioswift_swift3_version: "{{ openio_swift_swift3_version }}"

...
