---
- name: Install redis nodes
  hosts: redis
  gather_facts: false
  become: true
  pre_tasks:
    - name: refresh facts
      setup:
      when: ansible_default_ipv4 is not defined
  roles:
    - role: redis
      openio_redis_namespace: "{{ namespace }}"
      openio_redis_master:
        address: "{{ hostvars[ groups['redis'][0] ]['ansible_' + openio_bind_interface ]['ipv4']['address'] }}"
        port: 6011

    - role: redis
      openio_redis_mode: sentinel
      openio_redis_namespace: "{{ namespace }}"
...
